name: Telegram Bot

on:
  push:
    branches:
      - main  # Chỉ chạy khi có push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot
      working-directory: ${{ github.workspace }}  # Sử dụng thư mục làm việc mặc định của GitHub

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python telegram_bot.py
