name: Telegram Bot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install telebot library
      run: pip install telebot

    - name: Run your bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python test.py
